config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(flat) do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :address, class: "form-label" %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :address, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :number_of_guests, class: "form-label" %>
    <%= f.number_field :number_of_guests, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :price_per_night, class: "form-label" %>
    <%= f.number_field :price_per_night, class: 'form-control' %>
  </div>
  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn btn-danger ms-2' %>
  </div>
<% end %>

app/views/flats/index.html.erb
<h1>All our Flats (<%= @flats.count %>)</h1>

<div class="row">
  <% @flats.each do |flat| %>
    <div class="col-md-4">
      <div class="flat-card">
        <div class="flat-card-image"></div>
        <div class="flat-card-content">
          <div class="flat-card-title">
            <h4><%= flat.name %></h4>
          </div>
          <p><%= flat.address %></p>
          <div>
            <div class="flex">
              <i class="material-icons me-2">group</i><span><%= flat.number_of_guests %></span>
              <i class="material-icons me-2 ms-3">euro_symbol</i><span><%= flat.price_per_night %></span>
            </div>
          </div>
        </div>
        <div class="flat-card-actions">
          <%= link_to 'More info', flat_path(flat) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <div class="mt-3">
          <%= render "form", flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/15e70f61ae.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-house"></i>
      Simple Airbnb
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="ms-auto flex">
        <form class="flex my-2 my-lg-0">
          <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <%= link_to 'Add Flat', new_flat_path, class: 'btn btn-outline-primary my-2 my-sm-0 ms-2' %>
      </div>
    </div>
  </div>
</nav>